// Mock Data — ข้อมูลสมมุติสำหรับ TRD-LEX Demo
export const mockListings = [
  {
    id: "TRD-2024-001",
    contractNo: "สธ.กท.60/2558",
    title: "พื้นที่พาณิชยกรรม ย่านบางรัก ติดถนนสีลม",
    location: {
      province: "กรุงเทพมหานคร",
      district: "บางรัก",
      subdistrict: "สีลม",
      address: "ถนนสีลม แขวงสีลม เขตบางรัก",
      lat: 13.7246,
      lng: 100.5296,
    },
    area: 240,
    areaUnit: "ตร.ม.",
    zoneType: "พาณิชยกรรม",
    leaseYearsRemaining: 18,
    leaseExpiryYear: 2042,
    monthlyRent: 28000,
    transferPrice: 3500000,
    images: ["/images/listing-01-a.jpg", "/images/listing-01-b.jpg"],
    description:
      "พื้นที่เช่าราชพัสดุทำเลทอง ย่านสีลม เหมาะสำหรับร้านค้า ออฟฟิศขนาดเล็ก หรือร้านอาหาร สภาพแวดล้อมดี ใกล้ BTS สีลม เดินได้ภายใน 3 นาที อาคารสภาพดี มีที่จอดรถ 2 คัน",
    seller: {
      name: "นายสมชาย วิริยะกุล",
      verified: true,
      phone: "08x-xxx-xxxx",
    },
    verified: true,
    status: "active",
    views: 1284,
    interests: 23,
    listedDate: "2025-03-15",
    features: ["ใกล้ BTS", "มีที่จอดรถ"],
    utilities: ["ไฟฟ้า 3 เฟส (100A)", "ระบบน้ำประปานครหลวง", "AIS Fibre 1Gbps / WiFi", "True 5G Ready"],
    zoning: {
      color: "แดง",
      colorCode: "#e11d48",
      code: "พ.๕-๓",
      name: "ที่ดินประเภทพาณิชยกรรม (สีแดง)",
      desc: "ศูนย์กลางธุรกิจ การค้า บริการ และที่อยู่อาศัยหนาแน่นสูงพิเศษ",
      far: "10:1",
      osr: "3%",
      restriction: "ห้ามประกอบกิจการประเภทโรงงานอุตสาหกรรม, คลังสินค้าขนาดใหญ่, และฟาร์มเลี้ยงสัตว์เชิงพาณิชย์"
    },
  },
  {
    id: "TRD-2024-002",
    contractNo: "สธ.ชม.12/2562",
    title: "ที่ดินเกษตรกรรม จ.เชียงใหม่ แม่ริม",
    location: {
      province: "เชียงใหม่",
      district: "แม่ริม",
      subdistrict: "ริมใต้",
      address: "ต.ริมใต้ อ.แม่ริม จ.เชียงใหม่",
      lat: 18.8893,
      lng: 98.9442,
    },
    area: 3200,
    areaUnit: "ตร.ม.",
    zoneType: "เกษตรกรรม",
    leaseYearsRemaining: 24,
    leaseExpiryYear: 2048,
    monthlyRent: 4500,
    transferPrice: 450000,
    images: ["/images/listing-02-a.jpg"],
    description:
      "ที่ดินราชพัสดุ เหมาะสำหรับทำการเกษตร สวนผลไม้ หรือฟาร์มออร์แกนิค น้ำชลประทานเข้าถึง ทำเลห่างจากตัวเมืองเชียงใหม่ประมาณ 15 กม.",
    seller: {
      name: "นางสาวมาลี เกษตรไทย",
      verified: true,
      phone: "09x-xxx-xxxx",
    },
    verified: true,
    status: "active",
    views: 756,
    interests: 11,
    listedDate: "2025-04-02",
    features: ["ทางเข้าออกสะดวก", "ดินอุดมสมบูรณ์"],
    utilities: ["ไฟฟ้าเกษตร 220V", "ระบบน้ำชลประทานเพื่อการเกษตร", "3BB Fibre 500Mbps"],
    zoning: {
      color: "เขียว",
      colorCode: "#16a34a",
      code: "ก.๑-๕",
      name: "ที่ดินประเภทชนบทและเกษตรกรรม (สีเขียว)",
      desc: "สงวนไว้สำหรับเกษตรกรรม การปศุสัตว์ และการอนุรักษ์พื้นที่ป่าไม้",
      far: "1:1",
      osr: "40%",
      restriction: "ห้ามสร้างอาคารสิ่งปลูกสร้างสูงเกิน 12 เมตร, อาคารพาณิชย์ขนาดใหญ่พิเศษ หรือโรงงานอุตสาหกรรมเคมี"
    },
  },
  {
    id: "TRD-2024-003",
    contractNo: "สธ.กท.98/2561",
    title: "ห้องแถว 3 คูหา ย่านเยาวราช-วังบูรพา",
    location: {
      province: "กรุงเทพมหานคร",
      district: "สัมพันธวงศ์",
      subdistrict: "จักรวรรดิ",
      address: "ถนนจักรวรรดิ แขวงจักรวรรดิ เขตสัมพันธวงศ์",
      lat: 13.7392,
      lng: 100.5093,
    },
    area: 180,
    areaUnit: "ตร.ม.",
    zoneType: "พาณิชยกรรม",
    leaseYearsRemaining: 12,
    leaseExpiryYear: 2036,
    monthlyRent: 22000,
    transferPrice: 1800000,
    images: ["/images/listing-03-a.jpg"],
    description:
      "ห้องแถว 3 คูหา 2 ชั้น ย่านเยาวราช ทำเลค้าขายชั้นดี ศักยภาพสูง เหมาะกับธุรกิจค้าส่ง ร้านอาหาร หรือ โกดังเก็บสินค้า",
    seller: {
      name: "นายประสิทธิ์ พาณิชยการ",
      verified: true,
      phone: "08x-xxx-xxxx",
    },
    verified: true,
    status: "active",
    views: 2103,
    interests: 47,
    listedDate: "2025-02-18",
    features: ["ย่านธุรกิจ", "3 คูหา", "2 ชั้น", "ใกล้รถไฟฟ้า MRT"],
    utilities: ["ไฟฟ้า 3 เฟส (50A)", "ระบบน้ำประปานครหลวง", "True Online Fibre 1Gbps", "AIS 5G Ready"],
    zoning: {
      color: "แดง",
      colorCode: "#e11d48",
      code: "พ.๔-๕",
      name: "ที่ดินประเภทพาณิชยกรรม (สีแดง)",
      desc: "ย่านการค้าหนาแน่นสูงและการอนุรักษ์วัฒนธรรมเมืองเก่า",
      far: "8:1",
      osr: "4%",
      restriction: "ข้อบังคับเขตพระนคร/สัมพันธวงศ์: จำกัดความสูงอาคารไม่เกิน 16 เมตร และต้องใช้วัสดุและโทนสีที่กลมกลืนกับสถาปัตยกรรมย่านประวัติศาสตร์"
    },
  },
  {
    id: "TRD-2024-004",
    contractNo: "สธ.สข.05/2563",
    title: "ที่ดินติดชายหาด จ.สงขลา อ.สิงหนคร",
    location: {
      province: "สงขลา",
      district: "สิงหนคร",
      subdistrict: "ชิงโค",
      address: "ต.ชิงโค อ.สิงหนคร จ.สงขลา",
      lat: 7.2136,
      lng: 100.5972,
    },
    area: 1600,
    areaUnit: "ตร.ม.",
    zoneType: "ท่องเที่ยวและพักผ่อน",
    leaseYearsRemaining: 20,
    leaseExpiryYear: 2043,
    monthlyRent: 15000,
    transferPrice: 2200000,
    images: ["/images/listing-04-a.jpg"],
    description:
      "ที่ดินราชพัสดุติดชายหาด เหมาะสำหรับรีสอร์ท โรงแรมขนาดเล็ก หรือร้านอาหารซีฟู้ด วิวทะเลสาบสงขลา ศักยภาพการท่องเที่ยวสูง",
    seller: {
      name: "นายวิเชียร ทะเลใต้",
      verified: false,
      phone: "08x-xxx-xxxx",
    },
    verified: false,
    status: "pending",
    views: 934,
    interests: 19,
    listedDate: "2025-05-01",
    features: ["ติดชายหาด", "วิวทะเล", "ศักยภาพท่องเที่ยว"],
    utilities: ["ระบบไฟฟ้าส่วนภูมิภาค 220V", "ระบบน้ำประปาส่วนภูมิภาค", "AIS 5G / True 5G Ready (เสาสัญญาณชายหาด)"],
    zoning: {
      color: "ฟ้า",
      colorCode: "#2563eb",
      code: "ล.๑",
      name: "ที่ดินประเภทอนุรักษ์เพื่อการท่องเที่ยว (สีฟ้า)",
      desc: "ส่งเสริมและรักษาคุณภาพสิ่งแวดล้อม ศิลปวัฒนธรรม และการท่องเที่ยวชายหาด",
      far: "2:1",
      osr: "20%",
      restriction: "กฎกระทรวงควบคุมอาคารริมทะเล: ห้ามก่อสร้างอาคารที่มีความสูงเกิน 12 เมตรในระยะ 150 เมตรจากแนวชายหาด และต้องเว้นพื้นที่ว่างเปิดโล่งตามกฎหมายสิ่งแวดล้อม"
    },
  },
  {
    id: "TRD-2024-005",
    contractNo: "สธ.ขก.33/2560",
    title: "อาคารพาณิชย์ ย่านตลาดเมือง ขอนแก่น",
    location: {
      province: "ขอนแก่น",
      district: "เมืองขอนแก่น",
      subdistrict: "ในเมือง",
      address: "ถนนกลางเมือง ต.ในเมือง อ.เมือง จ.ขอนแก่น",
      lat: 16.4419,
      lng: 102.8358,
    },
    area: 320,
    areaUnit: "ตร.ม.",
    zoneType: "พาณิชยกรรม",
    leaseYearsRemaining: 15,
    leaseExpiryYear: 2039,
    monthlyRent: 18000,
    transferPrice: 1200000,
    images: ["/images/listing-05-a.jpg"],
    description:
      "อาคารพาณิชย์ 2 ชั้น ย่านตลาดใจกลางเมืองขอนแก่น ใกล้ศาลากลางจังหวัด เหมาะสำหรับธุรกิจค้าปลีก สำนักงาน หรือร้านอาหาร",
    seller: {
      name: "นางสุดใจ อีสานแลนด์",
      verified: true,
      phone: "09x-xxx-xxxx",
    },
    verified: true,
    status: "active",
    views: 1567,
    interests: 34,
    listedDate: "2025-01-22",
    features: ["ใจกลางเมือง", "ใกล้ศาลากลาง", "2 ชั้น", "ลานจอดรถ"],
    utilities: ["ไฟฟ้า 3 เฟส", "ระบบน้ำประปาส่วนภูมิภาค", "3BB Fibre", "AIS 5G / True 5G"],
    zoning: {
      color: "แดง",
      colorCode: "#e11d48",
      code: "พ.๓-๒",
      name: "ที่ดินประเภทพาณิชยกรรม (สีแดง)",
      desc: "ย่านการค้าและศูนย์กลางชุมชนระดับเมืองขอนแก่น",
      far: "6:1",
      osr: "5%",
      restriction: "ห้ามประกอบกิจการที่เป็นอันตรายต่อชุมชน หรือโรงงานที่ไม่ได้มาตรฐานการจัดการน้ำเสีย"
    },
  },
  {
    id: "TRD-2024-006",
    contractNo: "สธ.กท.147/2564",
    title: "พื้นที่ Market ริมแม่น้ำ เจ้าพระยา ย่านบางโพ",
    location: {
      province: "กรุงเทพมหานคร",
      district: "บางซื่อ",
      subdistrict: "บางโพ",
      address: "ริมแม่น้ำเจ้าพระยา ย่านบางโพ เขตบางซื่อ",
      lat: 13.8121,
      lng: 100.5043,
    },
    area: 800,
    areaUnit: "ตร.ม.",
    zoneType: "พาณิชยกรรม",
    leaseYearsRemaining: 22,
    leaseExpiryYear: 2046,
    monthlyRent: 45000,
    transferPrice: 5800000,
    images: ["/images/listing-06-a.jpg"],
    description:
      "พื้นที่ขนาดใหญ่ติดริมแม่น้ำเจ้าพระยา วิวแม่น้ำสวยงาม เหมาะสำหรับพัฒนาเป็น Community Mall ร้านอาหาร Waterfront หรือ Co-working Space ขนาดใหญ่",
    seller: {
      name: "บริษัท เจ้าพระยาดีเวลลอปเมนท์ จำกัด",
      verified: true,
      phone: "02-xxx-xxxx",
    },
    verified: true,
    status: "active",
    views: 3421,
    interests: 89,
    listedDate: "2025-06-10",
    features: ["ติดแม่น้ำ", "วิวแม่น้ำ", "พื้นที่ใหญ่", "ท่าเทียบเรือ"],
    utilities: ["ไฟฟ้า 3 เฟส (200A) รองรับ EV Charger", "ระบบน้ำประปานครหลวงแรงดันสูง", "AIS Fibre 1Gbps", "True Online Fibre / เสา 5G ริมแม่น้ำ"],
    zoning: {
      color: "น้ำตาล",
      colorCode: "#78350f",
      code: "ย.๙-๑๐",
      name: "ที่ดินประเภทที่อยู่อาศัยหนาแน่นมาก (สีน้ำตาล)",
      desc: "ที่อยู่อาศัยหนาแน่นสูง และส่งเสริมการพัฒนาเมืองริมตลิ่งแม่น้ำเจ้าพระยา",
      far: "8:1",
      osr: "4%",
      restriction: "พ.ร.บ.ควบคุมอาคารและกฎกระทรวงริมน้ำ: กำหนดระยะถอยร่นจากแนวตลิ่งแม่น้ำเจ้าพระยาอย่างน้อย 15 เมตรสำหรับการก่อสร้างอาคาร และต้องมีการประเมินผลกระทบสิ่งแวดล้อม (EIA) สำหรับโครงการขนาดใหญ่"
    },
  },
];

export const mockStats = {
  totalListings: 1284,
  activeListings: 987,
  completedTransfers: 342,
  totalProvinces: 47,
  newThisMonth: 89,
  expressInterestThisMonth: 234,
};

export const mockAdminStats = {
  pendingApproval: 23,
  activeListings: 987,
  expressedInterest: 1456,
  completedTransfers: 342,
  revenueEstimate: 8420000,
  monthlyData: [
    { month: "ม.ค.", listings: 62, transfers: 18 },
    { month: "ก.พ.", listings: 75, transfers: 24 },
    { month: "มี.ค.", listings: 88, transfers: 31 },
    { month: "เม.ย.", listings: 95, transfers: 28 },
    { month: "พ.ค.", listings: 110, transfers: 42 },
    { month: "มิ.ย.", listings: 89, transfers: 35 },
    { month: "ก.ค.", listings: 124, transfers: 56 },
  ],
  topProvinces: [
    { name: "กรุงเทพมหานคร", count: 312 },
    { name: "เชียงใหม่", count: 87 },
    { name: "ขอนแก่น", count: 65 },
    { name: "สงขลา", count: 54 },
    { name: "ชลบุรี", count: 48 },
  ],
};

export const provinces = [
  "กรุงเทพมหานคร", "เชียงใหม่", "เชียงราย", "ขอนแก่น", "อุดรธานี",
  "นครราชสีมา", "อุบลราชธานี", "สงขลา", "ภูเก็ต", "สุราษฎร์ธานี",
  "ชลบุรี", "ระยอง", "นนทบุรี", "ปทุมธานี", "สมุทรปราการ",
  "นครปฐม", "อยุธยา", "สระบุรี", "ลพบุรี", "สุพรรณบุรี",
];

export const zoneTypes = [
  "ทั้งหมด", "พาณิชยกรรม", "เกษตรกรรม", "ที่อยู่อาศัย",
  "อุตสาหกรรม", "ท่องเที่ยวและพักผ่อน",
];

export const feeConfig = {
  transferFeeRate: 0.025,      // 2.5% ของมูลค่าค่าตอบแทน
  stampDutyRate: 0.005,        // 0.5%
  withholdingTaxRate: 0.01,    // 1% (สำหรับบุคคลธรรมดา)
  vatRate: 0.07,               // 7% เฉพาะกรณีนิติบุคคล
};
